// This file is auto-generated by generate_adder_tree.py. DO NOT EDIT.

#include "accelerator_utils.h" // For fp32_add_propagate_specials

inline ap_uint<32> hls_private_final_reduction_sum(ap_uint<32> inputs[48]) {
    #pragma HLS INLINE
    ap_uint<32> stage[48];
    #pragma HLS ARRAY_PARTITION variable=stage complete

    for(int i=0; i<48; ++i) stage[i] = inputs[i];

    // Level 0: 48 -> 24
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[24]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[25]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[26]);
        stage[3] = fp32_add_propagate_specials(stage[3], stage[27]);
        stage[4] = fp32_add_propagate_specials(stage[4], stage[28]);
        stage[5] = fp32_add_propagate_specials(stage[5], stage[29]);
        stage[6] = fp32_add_propagate_specials(stage[6], stage[30]);
        stage[7] = fp32_add_propagate_specials(stage[7], stage[31]);
        stage[8] = fp32_add_propagate_specials(stage[8], stage[32]);
        stage[9] = fp32_add_propagate_specials(stage[9], stage[33]);
        stage[10] = fp32_add_propagate_specials(stage[10], stage[34]);
        stage[11] = fp32_add_propagate_specials(stage[11], stage[35]);
        stage[12] = fp32_add_propagate_specials(stage[12], stage[36]);
        stage[13] = fp32_add_propagate_specials(stage[13], stage[37]);
        stage[14] = fp32_add_propagate_specials(stage[14], stage[38]);
        stage[15] = fp32_add_propagate_specials(stage[15], stage[39]);
        stage[16] = fp32_add_propagate_specials(stage[16], stage[40]);
        stage[17] = fp32_add_propagate_specials(stage[17], stage[41]);
        stage[18] = fp32_add_propagate_specials(stage[18], stage[42]);
        stage[19] = fp32_add_propagate_specials(stage[19], stage[43]);
        stage[20] = fp32_add_propagate_specials(stage[20], stage[44]);
        stage[21] = fp32_add_propagate_specials(stage[21], stage[45]);
        stage[22] = fp32_add_propagate_specials(stage[22], stage[46]);
        stage[23] = fp32_add_propagate_specials(stage[23], stage[47]);
    }

    // Level 1: 24 -> 12
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[12]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[13]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[14]);
        stage[3] = fp32_add_propagate_specials(stage[3], stage[15]);
        stage[4] = fp32_add_propagate_specials(stage[4], stage[16]);
        stage[5] = fp32_add_propagate_specials(stage[5], stage[17]);
        stage[6] = fp32_add_propagate_specials(stage[6], stage[18]);
        stage[7] = fp32_add_propagate_specials(stage[7], stage[19]);
        stage[8] = fp32_add_propagate_specials(stage[8], stage[20]);
        stage[9] = fp32_add_propagate_specials(stage[9], stage[21]);
        stage[10] = fp32_add_propagate_specials(stage[10], stage[22]);
        stage[11] = fp32_add_propagate_specials(stage[11], stage[23]);
    }

    // Level 2: 12 -> 6
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[6]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[7]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[8]);
        stage[3] = fp32_add_propagate_specials(stage[3], stage[9]);
        stage[4] = fp32_add_propagate_specials(stage[4], stage[10]);
        stage[5] = fp32_add_propagate_specials(stage[5], stage[11]);
    }

    // Level 3: 6 -> 3
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[3]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[4]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[5]);
    }

    // Level 4: 3 -> 2
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[1]);
        stage[1] = stage[2];
    }

    // Level 5: 2 -> 1
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[1]);
    }

    return stage[0];
}

inline ap_uint<32> hls_private_final_reduction_sum_sq(ap_uint<32> inputs[48]) {
    #pragma HLS INLINE
    ap_uint<32> stage[48];
    #pragma HLS ARRAY_PARTITION variable=stage complete

    for(int i=0; i<48; ++i) stage[i] = inputs[i];

    // Level 0: 48 -> 24
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[24]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[25]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[26]);
        stage[3] = fp32_add_propagate_specials(stage[3], stage[27]);
        stage[4] = fp32_add_propagate_specials(stage[4], stage[28]);
        stage[5] = fp32_add_propagate_specials(stage[5], stage[29]);
        stage[6] = fp32_add_propagate_specials(stage[6], stage[30]);
        stage[7] = fp32_add_propagate_specials(stage[7], stage[31]);
        stage[8] = fp32_add_propagate_specials(stage[8], stage[32]);
        stage[9] = fp32_add_propagate_specials(stage[9], stage[33]);
        stage[10] = fp32_add_propagate_specials(stage[10], stage[34]);
        stage[11] = fp32_add_propagate_specials(stage[11], stage[35]);
        stage[12] = fp32_add_propagate_specials(stage[12], stage[36]);
        stage[13] = fp32_add_propagate_specials(stage[13], stage[37]);
        stage[14] = fp32_add_propagate_specials(stage[14], stage[38]);
        stage[15] = fp32_add_propagate_specials(stage[15], stage[39]);
        stage[16] = fp32_add_propagate_specials(stage[16], stage[40]);
        stage[17] = fp32_add_propagate_specials(stage[17], stage[41]);
        stage[18] = fp32_add_propagate_specials(stage[18], stage[42]);
        stage[19] = fp32_add_propagate_specials(stage[19], stage[43]);
        stage[20] = fp32_add_propagate_specials(stage[20], stage[44]);
        stage[21] = fp32_add_propagate_specials(stage[21], stage[45]);
        stage[22] = fp32_add_propagate_specials(stage[22], stage[46]);
        stage[23] = fp32_add_propagate_specials(stage[23], stage[47]);
    }

    // Level 1: 24 -> 12
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[12]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[13]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[14]);
        stage[3] = fp32_add_propagate_specials(stage[3], stage[15]);
        stage[4] = fp32_add_propagate_specials(stage[4], stage[16]);
        stage[5] = fp32_add_propagate_specials(stage[5], stage[17]);
        stage[6] = fp32_add_propagate_specials(stage[6], stage[18]);
        stage[7] = fp32_add_propagate_specials(stage[7], stage[19]);
        stage[8] = fp32_add_propagate_specials(stage[8], stage[20]);
        stage[9] = fp32_add_propagate_specials(stage[9], stage[21]);
        stage[10] = fp32_add_propagate_specials(stage[10], stage[22]);
        stage[11] = fp32_add_propagate_specials(stage[11], stage[23]);
    }

    // Level 2: 12 -> 6
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[6]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[7]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[8]);
        stage[3] = fp32_add_propagate_specials(stage[3], stage[9]);
        stage[4] = fp32_add_propagate_specials(stage[4], stage[10]);
        stage[5] = fp32_add_propagate_specials(stage[5], stage[11]);
    }

    // Level 3: 6 -> 3
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[3]);
        stage[1] = fp32_add_propagate_specials(stage[1], stage[4]);
        stage[2] = fp32_add_propagate_specials(stage[2], stage[5]);
    }

    // Level 4: 3 -> 2
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[1]);
        stage[1] = stage[2];
    }

    // Level 5: 2 -> 1
    {
        stage[0] = fp32_add_propagate_specials(stage[0], stage[1]);
    }

    return stage[0];
}
